version: '3.8'

services:
  xfs-quota-kit:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: xfs-quota-kit
    hostname: xfs-quota-kit
    privileged: true  # 需要特权模式访问文件系统
    volumes:
      - /mnt:/mnt:rw  # 挂载宿主机的文件系统
      - ./config:/etc/xfs-quota-kit:ro  # 挂载配置文件
      - logs:/var/log/xfs-quota-kit  # 日志卷
      - backups:/var/backups/xfs-quota-kit  # 备份卷
    environment:
      - XFS_QUOTA_LOGGING_LEVEL=info
      - XFS_QUOTA_SERVER_PORT=8080
      - XFS_QUOTA_DEFAULT_PATH=/mnt/xfs
    ports:
      - "8080:8080"  # API 服务器端口
    networks:
      - quota-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./xfs-quota-kit", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["./xfs-quota-kit", "server", "--config", "/etc/xfs-quota-kit/config.yaml"]

  # 可选：监控服务
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - quota-network
    restart: unless-stopped
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - quota-network
    restart: unless-stopped
    profiles:
      - monitoring

  # 可选：日志聚合
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - quota-network
    restart: unless-stopped
    profiles:
      - logging

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - quota-network
    restart: unless-stopped
    depends_on:
      - elasticsearch
    profiles:
      - logging

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    container_name: logstash
    volumes:
      - ./monitoring/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./monitoring/logstash/config:/usr/share/logstash/config:ro
      - logs:/var/log/xfs-quota-kit:ro
    networks:
      - quota-network
    restart: unless-stopped
    depends_on:
      - elasticsearch
    profiles:
      - logging

networks:
  quota-network:
    driver: bridge

volumes:
  logs:
    driver: local
  backups:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  elasticsearch-data:
    driver: local 